name: Lint
run-name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: actions/checkout@v1
      - name: Lint bash scripts
        uses: Azbagheri/shell-linter@latest
        with:
          exclude-paths: "LICENSE"
      - name: Lint bash script conding styles
        uses: collin-miller/shfmt-action@v1
        with:
          args: -d -i 2 -sr -ln=bash .
      - name: Validate composer.json
        run: composer validate --no-check-publish --strict
