name: Lint
run-name: Lint

on: [push, pull_request]

jobs:
  lint:
    # src: https://www.shellcheck.net/wiki/GitHub-Actions
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # required for uploading SARIF results
      contents: read
    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: actions/checkout@v1
      - name: Run ShellCheck with SARIF output
        uses: reactive-firewall/shellcheck-scan@v1
      - name: Validate composer.json
        run: composer validate --no-check-publish --strict
